apiVersion: v2
name: pvcautoscaler
description: A Helm chart for PVCAutoscaler
maintainers:
  - name: mkihr
    email: matthias@kihr.online
    url: https://github.com/mkihr

type: application
version: 0.3.2
appVersion: 0.3.2
