image:
  # image.repository -- pvc-autoscaler image repository to use.
  repository: mkihr/pvc-autoscaler

  # image.tag -- pvc-autoscaler image tag to use.
  tag: "latest"

  # image.pullPolicy -- pvc-autoscaler image pullPolicy.
  pullPolicy: Always

pvcAutoscaler:
  args:
    # pvcAutoscaler.args.metricsClient -- Specify the metrics client to use to query volume stats.
    # Used as "--metrics-client" option
    metricsClient: "prometheus"

    # pvcAutoscaler.args.metricsClientURL -- Specify metrics client URL to query volume stats.
    # Used as "--metrics-client-url" option
    metricsClientURL: http://prometheus-operated.prom.svc.cluster.local:9090

    # pvcAutoscaler.args.pollingInterval -- Specify how often to check pvc stats.
    # Used as "--polling-interval" option
    pollingInterval: 30s

    # pvcAutoscaler.args.reconcileTimeout -- Specify the time after which the reconciliation is considered failed.
    # Used as "--reconcile-timeout" option
    reconcileTimeout: 30s

    # avoid TLS errors when using self-signed certs
    # pvcAutoscaler.args.insecureSkipVerify -- Skip TLS certificate verification when connecting to metrics
    # Used as "--insecure-skip-verify" option
    insecureSkipVerify: false

    # pvcAutoscaler.args.bearerTokenFile -- Path to bearer token file for Prometheus authentication
    # For OpenShift, use the ServiceAccount token: /var/run/secrets/kubernetes.io/serviceaccount/token
    # Used as "--bearer-token-file" option
    bearerTokenFile: ""

    logger:
       # pvcAutoscaler.logger.logLevel -- Specify the log level.
      logLevel: "INFO"

    # pvcAutoscaler.extraLabels -- Additional labels that will be added to pvc-autoscaler Deployment.
    extraLabels: {}

  # pvcAutoscaler.resources -- Specify resources for pvc-autoscaler deployment
  resources:
    # pvcAutoscaler.resources.requestCPU -- Request CPU resource unit in terms of millicpu
    requestCPU: "10m"

    # pvcAutoscaler.resources.requestMemory -- Request memory resource unit in terms of Mi
    requestMemory: "20Mi"

# OpenShift specific configuration
openshift:
  # openshift.enabled -- Enable OpenShift-specific configurations (e.g., Prometheus RBAC)
  enabled: false
